### ISSUE TITLE
JPA DB연결정보

### ISSUE THREAD

**Issue by choisungwook** [choisungwook/springboot-jasypt#4]
* application.yaml설정
```yaml
spring:
  datasource:
    url: jdbc:mariadb://localhost:<포트번호>/<db이름>
    driver-class-name: org.mariadb.jdbc.Driver
    username: <계정이름>
    password: <비밀번호>
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
```
